### ISSUE TITLE
optimal ip ban issue

### ISSUE THREAD

**Issue by pythagorea1** [tareqmahmud/IMDBScraping#1]
I only see the software using randInt to avoid ip ban, however it seems the software takes a long time to finish collecting data by using randInt. Do you have any other idea to avoid IP ban and improve the efficiency of collection?

**Comment by tareqmahmud** [comment]
Yes, randInt makes the crawler slower. For that, I have some plan like use proxy services, add user agent spoofing & optimize the code to follow the exact rules like robots.txt and crawling the site by scheduling so that it can't differentiate between search engine robot & scraper. I'll add those features soon.
